# Generated by Django 5.0 on 2023-12-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='course',
            field=models.IntegerField(default=1, verbose_name='Курс'),
        ),
    ]
